language: ruby
rvm:
  - 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: ZQ5YlaExNyEcQptIU8bEBwVkTbUC2VvEQTpyBqe3maL6tAweF63bRx2UwfGrXbxnNIDWpm+BfUocOeTawWZ4ISFdOhupRhZzlg+EW1jcLtWWS2UeHfr2dha+4wsDfbCZ2E/8t/D+XAN2vpbso2Eh5p1pckDHyDY05vnyFCR0iq10250Q5q0rOK0TH6zvT13p1RyPfn8w6AHLOr4d0PWZa0c0/ByL3tgeEYa7T2f3JvYx0PRQU2na33M0xmqUvpLeAjhV1SlTb90TWA3I2Li44nzDtN9VyCQNCK3YE/WMoStVZEQchdl1CckQG0yEgnJL+4lA3CdmtODgvhZh/bx6rrKHHDe6la7UFa3a5MdBhmf08wya2NpIfo/tqN+dh/lDyqZSr2hDf7Da7D13LqdaVezRLGm8/YnjgvC3hX2WzVVqAho1p7DJzmllY938VJqeWpsVDYgJdc4ofFfCbeoZVDTZz3EZfpa4fOG1mwtBFJYvO0lINF3fuT/ESMeZPU5vpHvOpAv78qz3T+mY1kJ0GGW+04EbFLRfcL35CMdcOIaUnU2EeMrjP68YWiG6l9Koa64PN6i2FN9cnBceSlXf713rO0/XJ+5p88iDPvn/WtfMwUvigW3Z9aMzAqfns6ECoiUXpmcTNvKyKQNuVPAJP0WEJ3LcxyTpcX9FnANWpts=
