default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: homepage_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: homepage_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: homepage_production
  username: homepage
  password: <%= ENV['HOMEPAGE_DATABASE_PASSWORD'] %>
